export const WORDS = [
  "bird",
  "sky",
  "cloud",
  "wind",
  "nest",
  "feather",
  "wing",
  "song",
  "sunny",
  "breeze",
  "flock",
  "leaf",
  "river",
  "hill",
  "quick",
  "brave",
  "gentle",
  "happy",
  "bright",
  "float",
  "glide",
  "dance",
  "dream",
  "type",
  "speed",
  "focus",
  "rhythm",
  "smooth",
  "keyboard",
  "practice",
  "letter",
  "finger",
  "home",
  "row",
  "space",
  "jump",
  "swoop",
  "morning",
  "meadow",
  "honey",
  "berry",
  "acorn",
  "pebble",
  "puddle",
  "sunset",
  "twilight",
  "whisper",
  "wander",
  "cozy",
  "spark",
  "orange",
  "green",
  "little",
  "friend",
  "story",
  "garden",
  "window",
  "lantern",
  "journey",
  "pocket",
];

export function makeWordQueue(count = 220): string[] {
  const out: string[] = [];
  for (let i = 0; i < count; i++) {
    out.push(WORDS[Math.floor(Math.random() * WORDS.length)]!);
  }
  return out;
}

export const BEGINNER_LESSONS = [
  {
    id: "home-row",
    title: "Home row basics",
    hint: "Rest your left fingers on A S D F and right fingers on J K L ;",
    text: "asdf jkl; asdf jkl; sad lad ask fall dad flask salad glad flask",
  },
  {
    id: "top-row",
    title: "Top row reach",
    hint: "Reach up with the same finger, then return gently back to home row.",
    text: "we try to type quiet words with tired pretty keys were red rope quote",
  },
  {
    id: "bottom-row",
    title: "Bottom row glide",
    hint: "Drop fingers downward naturally without shifting your wrist angle.",
    text: "zoo box van cab man coin zoom buzz calm plan back next move",
  },
  {
    id: "easy-words",
    title: "Easy little words",
    hint: "Keep your wrists relaxed and eyes on the screen.",
    text: "the sun is up and the little bird sings a soft song in the tall green tree",
  },
  {
    id: "punctuation",
    title: "Punctuation rhythm",
    hint: "Use your right pinky for semicolons and ring/middle for commas and periods.",
    text: "quick, quiet, calm; small steps, big flight. look ahead, breathe deep.",
  },
  {
    id: "sentences",
    title: "Whole sentences",
    hint: "Slow and steady beats fast and messy. Focus on unbroken rhythm.",
    text: "A cozy little bird flies over warm hills while the wind carries its happy song.",
  },
];
