// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  const SESSION_STORAGE_KEY = "typefly_local_auth_session";
  const PROFILES_KEY = "typefly_local_profiles";
  const RESULTS_KEY = "typefly-history";

  function getStoredSession() {
    if (typeof window === "undefined") return null;
    try {
      const raw = window.localStorage.getItem(SESSION_STORAGE_KEY);
      return raw ? JSON.parse(raw) : null;
    } catch {
      return null;
    }
  }

  function setStoredSession(session: unknown) {
    if (typeof window === "undefined") return;
    if (session) {
      window.localStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(session));
    } else {
      window.localStorage.removeItem(SESSION_STORAGE_KEY);
    }
    listeners.forEach((fn) => {
      try {
        fn("SIGNED_IN", session);
      } catch {
        /* ignore */
      }
    });
  }

  const listeners: Array<(event: string, session: unknown) => void> = [];

  const dummyAuth = {
    onAuthStateChange: (callback: (event: string, session: unknown) => void) => {
      listeners.push(callback);
      const current = getStoredSession();
      if (current) {
        window.setTimeout(() => callback("INITIAL_SESSION", current), 0);
      }
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              const idx = listeners.indexOf(callback);
              if (idx >= 0) listeners.splice(idx, 1);
            },
          },
        },
      };
    },
    getSession: async () => ({ data: { session: getStoredSession() }, error: null }),
    getUser: async () => {
      const session = getStoredSession();
      return { data: { user: session?.user ?? null }, error: null };
    },
    signOut: async () => {
      setStoredSession(null);
      return { error: null };
    },
    signInWithPassword: async ({ email }: { email: string; password?: string }) => {
      const namePart = email.split("@")[0] || "Flyer";
      const user = {
        id: `local_user_${email.replace(/[^a-zA-Z0-9]/g, "_")}`,
        email,
        user_metadata: { display_name: namePart },
        created_at: new Date().toISOString(),
      };
      const session = { user, access_token: "mock_jwt_token" };
      setStoredSession(session);
      return { data: { user, session }, error: null };
    },
    signUp: async ({
      email,
      options,
    }: {
      email: string;
      password?: string;
      options?: { data?: { display_name?: string } };
    }) => {
      const displayName = options?.data?.display_name || email.split("@")[0] || "Flyer";
      const user = {
        id: `local_user_${email.replace(/[^a-zA-Z0-9]/g, "_")}`,
        email,
        user_metadata: { display_name: displayName },
        created_at: new Date().toISOString(),
      };
      const session = { user, access_token: "mock_jwt_token" };
      setStoredSession(session);
      return { data: { user, session }, error: null };
    },
    signInWithOAuth: async ({ provider }: { provider: string }) => {
      const user = {
        id: "google_user_local",
        email: "pilot@typefly.test",
        user_metadata: { display_name: "Google Aviator" },
        created_at: new Date().toISOString(),
      };
      const session = { user, access_token: "mock_google_token", provider };
      setStoredSession(session);
      return { data: { user, session }, error: null };
    },
    resetPasswordForEmail: async (_email: string) => {
      return { data: {}, error: null };
    },
    setSession: async (tokens: unknown) => {
      setStoredSession(tokens);
      return { data: { session: tokens }, error: null };
    },
  };

  interface QueryBuilder {
    select: () => QueryBuilder;
    insert: (
      records: Record<string, unknown> | Record<string, unknown>[],
    ) => Promise<{ data: unknown; error: null }>;
    upsert: (
      records: Record<string, unknown> | Record<string, unknown>[],
    ) => Promise<{ data: unknown; error: null }>;
    update: (patch: Record<string, unknown>) => Promise<{ data: unknown; error: null }>;
    delete: () => QueryBuilder;
    eq: (field: string, val: unknown) => QueryBuilder;
    neq: () => QueryBuilder;
    order: () => QueryBuilder;
    limit: () => QueryBuilder;
    single: () => Promise<{ data: unknown; error: null }>;
    maybeSingle: () => Promise<{ data: unknown; error: null }>;
    then: (resolve: (val: { data: unknown[]; error: null }) => unknown) => Promise<unknown>;
  }

  const dummyFrom = (tableName: string): QueryBuilder => {
    let filterField: string | null = null;
    let filterVal: unknown = null;

    const builder: QueryBuilder = {
      select: () => builder,
      insert: async (records: Record<string, unknown> | Record<string, unknown>[]) => {
        if (typeof window !== "undefined") {
          try {
            const list = Array.isArray(records) ? records : [records];
            if (tableName === "profiles") {
              const raw = window.localStorage.getItem(PROFILES_KEY);
              const map = (raw ? JSON.parse(raw) : {}) as Record<string, Record<string, unknown>>;
              list.forEach((r) => {
                if (r["id"]) {
                  const id = r["id"] as string;
                  map[id] = { ...(map[id] || {}), ...r };
                }
              });
              window.localStorage.setItem(PROFILES_KEY, JSON.stringify(map));
            } else if (tableName === "test_results") {
              const raw = window.localStorage.getItem(RESULTS_KEY);
              const arr = (raw ? JSON.parse(raw) : []) as Record<string, unknown>[];
              list.forEach((r) => arr.unshift({ ...r, id: `res_${Date.now()}` }));
              window.localStorage.setItem(RESULTS_KEY, JSON.stringify(arr.slice(0, 50)));
            }
          } catch {
            /* ignore */
          }
        }
        return { data: records, error: null };
      },
      upsert: async (records: Record<string, unknown> | Record<string, unknown>[]) => {
        return builder.insert(records);
      },
      update: async (patch: Record<string, unknown>) => {
        if (typeof window !== "undefined" && tableName === "profiles" && filterVal) {
          try {
            const raw = window.localStorage.getItem(PROFILES_KEY);
            const map = (raw ? JSON.parse(raw) : {}) as Record<string, Record<string, unknown>>;
            map[filterVal as string] = { ...(map[filterVal as string] || {}), ...patch };
            window.localStorage.setItem(PROFILES_KEY, JSON.stringify(map));
          } catch {
            /* ignore */
          }
        }
        return { data: patch, error: null };
      },
      delete: () => builder,
      eq: (field: string, val: unknown) => {
        filterField = field;
        filterVal = val;
        return builder;
      },
      neq: () => builder,
      order: () => builder,
      limit: () => builder,
      single: async () => {
        if (tableName === "profiles" && typeof window !== "undefined") {
          const raw = window.localStorage.getItem(PROFILES_KEY);
          const map = raw ? JSON.parse(raw) : {};
          const item = filterVal ? map[filterVal as string] : null;
          return { data: item || null, error: null };
        }
        return { data: null, error: null };
      },
      maybeSingle: async () => {
        return builder.single();
      },
      then: (resolve: (val: { data: unknown[]; error: null }) => unknown) => {
        if (tableName === "profiles" && typeof window !== "undefined") {
          const raw = window.localStorage.getItem(PROFILES_KEY);
          const map = raw ? JSON.parse(raw) : {};
          const item = filterVal ? map[filterVal as string] : null;
          return Promise.resolve({ data: item ? [item] : [], error: null }).then(resolve);
        }
        if (tableName === "test_results" && typeof window !== "undefined") {
          const raw = window.localStorage.getItem(RESULTS_KEY);
          const arr = raw ? JSON.parse(raw) : [];
          return Promise.resolve({ data: arr, error: null }).then(resolve);
        }
        return Promise.resolve({ data: [], error: null }).then(resolve);
      },
    };
    return builder;
  };

  return {
    auth: dummyAuth,
    from: dummyFrom,
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing environment variable(s): ${missing.join(", ")}. Using mock client.`,
    );
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
